# Generated by Django 4.1.2 on 2023-06-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skola_app', '0007_language_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Deadline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
