# Generated by Django 4.1.2 on 2023-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skola_app', '0008_course_deadline_course_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
